### ISSUE TITLE
Upload excel file

### ISSUE THREAD

**Issue by kbrannan** [PythonCodersOR/part_distribution_plots#2]
Could you upload the excel file to the repo?

Thanks

**Comment by DEQecostel** [comment]
When I click "Upload File" I get a message saying Uploads are disabled and that I require push access to this repository. 

DAWG

**Comment by kbrannan** [comment]
Thx!

**Comment by kbrannan** [comment]
Try now

**Comment by kbrannan** [comment]
done!
